# Generated by Django 4.1.4 on 2023-06-24 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "association",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "caregiver",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Caregiverphone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "caregiverphone",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Chair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parcode", models.IntegerField(db_index=True, unique=True)),
                ("password", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "db_table": "chair",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100, null=True)),
                ("last_name", models.CharField(blank=True, max_length=100, null=True)),
                ("gender", models.CharField(blank=True, max_length=5, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "patient",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("pulse_rate", models.FloatField(blank=True, null=True)),
                ("oximeter", models.FloatField(blank=True, null=True)),
                ("created_date", models.DateField(blank=True, null=True)),
                ("created_time", models.TimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "sensor_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(blank=True, max_length=15, null=True)),
                ("longitude", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "chair",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="panel.chair",
                    ),
                ),
            ],
        ),
    ]
