# Generated by Django 4.1.4 on 2023-06-25 06:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"managed": False},
        ),
    ]
