# Generated by Django 4.1.4 on 2023-07-03 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0002_alter_location_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="location",
            table="location",
        ),
    ]
